// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartRecipeEngine.Infrastructure.Data;

#nullable disable

namespace SmartRecipeEngine.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310105149_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("SmartRecipeEngine.Domain.Entities.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("SmartRecipeEngine.Domain.Entities.ItemPriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultExpiryDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultUnit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LastCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("LastPurchased")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemName")
                        .IsUnique();

                    b.ToTable("ItemPriceHistories");
                });

            modelBuilder.Entity("SmartRecipeEngine.Domain.Entities.PantryStaple", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PantryStaples");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsEnabled = true,
                            Name = "Salt"
                        },
                        new
                        {
                            Id = 2,
                            IsEnabled = true,
                            Name = "Pepper"
                        },
                        new
                        {
                            Id = 3,
                            IsEnabled = true,
                            Name = "Olive Oil"
                        },
                        new
                        {
                            Id = 4,
                            IsEnabled = true,
                            Name = "Flour"
                        },
                        new
                        {
                            Id = 5,
                            IsEnabled = true,
                            Name = "Sugar"
                        },
                        new
                        {
                            Id = 6,
                            IsEnabled = true,
                            Name = "Butter"
                        },
                        new
                        {
                            Id = 7,
                            IsEnabled = true,
                            Name = "Garlic"
                        },
                        new
                        {
                            Id = 8,
                            IsEnabled = true,
                            Name = "Onion"
                        });
                });

            modelBuilder.Entity("SmartRecipeEngine.Domain.Entities.WasteRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WasteRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
